### ISSUE TITLE
Clean UP & Dockerization of eos2r5a

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos2r5a#4]

**Comment by samuelmaina** [comment]
Hello @GemmaTuron,
I have opened a PR. Can you have a look.

**Comment by GemmaTuron** [comment]
Perfect, let's keep an eye on the Actions runs, the PR is now merged

**Comment by GemmaTuron** [comment]
Please check the DockerHub run

**Comment by samuelmaina** [comment]
Okay

**Comment by samuelmaina** [comment]
@GemmaTuron , the build is failing at amd, with this error ` No such file or directory: '/root/eos/dest/eos2r5a/pack.py'` , I looked at the PR last commit and saw that I had added pack.py in the root.  I don't know what could have caused this.Any idea?

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 
Seems the workflow runs on the pre-merged version of the repo, I've rerun it manually and the error is not the same any more, please check and also read this issue: https://github.com/ersilia-os/eos74bo/issues/20

**Comment by samuelmaina** [comment]
Hi @GemmaTuron , I have made a PR, you can review it.

**Comment by miquelduranfrigola** [comment]
Thanks @samuelmaina - I have merged the PR, let's see if it works: https://github.com/ersilia-os/eos2r5a/actions

In any case, since we have updated workflows, I will run them again.

**Comment by samuelmaina** [comment]
Thanks @miquelduranfrigola , I am watching the actions.

**Comment by miquelduranfrigola** [comment]
Hello @samuelmaina - I am now running the action with the new workflows. Let's see if it works. We will update you all about the new workflows today.

**Comment by samuelmaina** [comment]
The workflows are not failling .Thanks  @miquelduranfrigola

**Comment by miquelduranfrigola** [comment]
@GemmaTuron - This model seems to be resolved. Please check

**Comment by GemmaTuron** [comment]
There seems to be an issue with the output of the model to csv?
@samuelmaina can you please provide an update on this?
